spring:
  application:
    name: tlias-web-management
  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      # 最大文件请求大小
      max-request-size: 100MB
      # 单个文件最大大小
      max-file-size: 10MB

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
#logging:
#  level:
#    org.springframework.jdbc.support.JdbcTransactionManager: debug
logging:
  level:
    root: INFO
    org:
      apache:
        tomcat: WARN # 隐藏 Tomcat 的详细日志
      springframework:
        web: INFO
    javax.management: WARN # 隐藏 RMI/JMX 相关的 DEBUG 日志


# 阿里云OSS
aliyun:
    oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket-name: java-ai-01-test1
        region: cn-beijing

